"""Recruitment mail models, sanitization, storage and model-based processing."""

from .models import (
    Candidate,
    CompanyCandidate,
    DeadlineCandidate,
    EmailMessage,
    JobCandidate,
    LinkCandidate,
    LocationCandidate,
    MailCategory,
    MailCursor,
    MailIdentity,
    MailModel,
    ParsedEmail,
    ParsedRecruitmentEmail,
    RecruitmentEmail,
    RecruitmentEmailCategory,
    RecruitmentEmailInput,
    RecruitmentMailResult,
    RecruitmentMessageCategory,
    TimeCandidate,
)
from .sanitization import (
    html_to_text,
    redact_sensitive,
    redact_sensitive_text,
    safe_html_to_text,
    strip_html,
)
from .storage import (
    RecruitmentEmailRecord,
    RecruitmentEmailStore,
    RecruitmentMail,
    RecruitmentMailCursorRecord,
    RecruitmentMailProcessingStatus,
    RecruitmentMailRecord,
    RecruitmentMailStore,
    RecruitmentMailSyncItemRecord,
    RecruitmentMailSyncRunRecord,
)
from .sync import RecruitmentMailSyncResult, RecruitmentMailSyncService
from .runtime import (
    MailRuntimeConfigurationError,
    mail_account_key,
    sync_configured_mail,
)
from .connectors import (
    ImapConnectionConfig,
    ImapReadOnlyConnector,
    MailConnector,
    MailConnectorError,
    MailFetchBatch,
)
from .association import (
    ApplicationMatch,
    ApplicationStageDraft,
    MailAuditEvidence,
    RecruitmentMailAssociation,
    ScheduleDraft,
    associate_recruitment_email,
    find_stale_company_only_match,
)
from .backfill import MailAuthenticationBackfillResult, backfill_mail_authentication

__all__ = [
    "ApplicationMatch",
    "ApplicationStageDraft",
    "MailAuditEvidence",
    "ImapConnectionConfig",
    "ImapReadOnlyConnector",
    "MailConnector",
    "MailConnectorError",
    "MailFetchBatch",
    "RecruitmentMailAssociation",
    "ScheduleDraft",
    "associate_recruitment_email",
    "find_stale_company_only_match",
    "Candidate",
    "CompanyCandidate",
    "DeadlineCandidate",
    "EmailMessage",
    "JobCandidate",
    "LinkCandidate",
    "LocationCandidate",
    "MailCategory",
    "MailCursor",
    "MailIdentity",
    "MailAuthenticationBackfillResult",
    "MailModel",
    "MailRuntimeConfigurationError",
    "ParsedEmail",
    "ParsedRecruitmentEmail",
    "RecruitmentEmail",
    "RecruitmentEmailCategory",
    "RecruitmentEmailInput",
    "RecruitmentEmailRecord",
    "RecruitmentEmailStore",
    "RecruitmentMail",
    "RecruitmentMailCursorRecord",
    "RecruitmentMailProcessingStatus",
    "RecruitmentMailRecord",
    "RecruitmentMailStore",
    "RecruitmentMailSyncItemRecord",
    "RecruitmentMailSyncRunRecord",
    "RecruitmentMailSyncResult",
    "RecruitmentMailSyncService",
    "RecruitmentMailResult",
    "RecruitmentMessageCategory",
    "TimeCandidate",
    "html_to_text",
    "mail_account_key",
    "backfill_mail_authentication",
    "redact_sensitive",
    "redact_sensitive_text",
    "safe_html_to_text",
    "strip_html",
    "sync_configured_mail",
]
